# general settings
name: FineTune_FeMaSR_lora_V7_whole
model_type: FeMaSRModel
scale: 4
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: BSRGANTrainDataset 
    dataroot_gt: /data/DF2K/HR
    dataroot_lq: /data/DF2K/LR/x4

    io_backend:
      type: disk

    gt_size: 256
    scale: 4
    use_resize_crop: true
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    batch_size_per_gpu: &bsz 8
    num_worker_per_gpu: 8 
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: 32 #*bsz

  val:
    name: General_Image_Valid
    type: PairedImageDataset 
    dataroot_gt: /data/bsrgan_plus/DIV2K_VAL/HR
    dataroot_lq: /data/bsrgan_plus/DIV2K_VAL/LR/x4

    use_flip: False
    use_rot: False
    io_backend:
      type: disk

# network structures
network_g:
  type: FeMaSRNet #_lora
  codebook_params: [[32, 1024, 512]]
  gt_resolution: 256
  LQ_stage: True
  scale_factor: 4

network_ldp:
  type: LDP
  in_nc: 3
  out_nc: 3
  upscale: 4
  d_model: 64
  Nd: 32
  DP_depth: 2
  diffloss_d: 3
  diffloss_w: 64
  diffusion_batch_mul: 1
  num_sampling_steps: '200'

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3

# path
path:
  pretrain_network_hq: /code/ex6/FeMaSR/experiments/pretrained_models/FeMaSR_HRP_model_g.pth
  pretrain_network_g: /code/ex6/FeMaSR/experiments/pretrained_models/FeMaSR_SRX4_model_g.pth
  pretrain_network_ldp: /code/ex12/LDP/experiments/LDP_dwtsr_bsrgan_dM64_Nd32_nst200/models/net_g_best_.pth
  pretrain_network_d: /code/ex6/FeMaSR/experiments/pretrained_models/FeMaSR_HRP_model_d.pth
  strict_load: false

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4 
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000,100000,150000,200000,250000,300000,350000,400000,450000,500000]
    gamma: 1

  total_iter: 100000 
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1
    reduction: mean

  fre_opt:
    type: FrequencyLoss
    loss_weight: !!float 10

  dwthf_opt:
    type: DWTHFLoss
    loss_weight_1: !!float 0.1
    loss_weight_2: !!float 0.1
    map_weight: 0.1

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
#     before relu
     'conv1_2': 0.1
     'conv2_2': 0.1
     'conv3_4': 1
     'conv4_4': 1
     'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1 
    style_weight: 0.0
    criterion: l1

  gan_opt:
    type: GANLoss
    gan_type: hinge
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 0.1

  net_d_iters: 1
  net_d_init_iters: !!float 0

# validation settings·
val:
  val_freq: !!float 1e3 
  save_img:  True

  key_metric: lpips
  metrics:
    psnr: # metric name, not used in this codebase
      type: psnr
      crop_border: 0
      test_y_channel: true
      color_space: ycbcr
    ssim:
      type: ssim
      crop_border: 0
      test_y_channel: true
      color_space: ycbcr
    lpips:
      type: lpips
      better: lower

# logging settings
logger:
  print_freq: 100 #100
  save_checkpoint_freq: !!float 1e9
  save_latest_freq: !!float 1e3 
  show_tf_imgs_freq: !!float 1e9
  use_tb_logger: true

